import React, { createContext, useContext, useState } from 'react';

const translations = {
  ro: {
    nav: {
      home: 'Acasă', services: 'Servicii', about: 'Despre noi',
      gallery: 'Galerie', location: 'Locație', login: 'Autentificare',
      register: 'Înregistrare', profile: 'Profil', logout: 'Deconectare', admin: 'Admin'
    },
    home: {
      hero1: 'Expertiza ta în sisteme auto & multimedia',
      hero2: 'Reparații rapide și profesionale',
      hero3: 'Calitate garantată, prețuri corecte',
      hero4: 'Servicii complete pentru mașina ta',
      cta: 'Vezi serviciile',
      whyUs: 'De ce să ne alegi?',
      years: 'Ani experiență',
      clients: 'Clienți mulțumiți',
      warranty: 'Garanție',
      brands: 'Mărci auto deservite',
      featuredServices: 'Servicii principale',
      bookNow: 'Programează-te',
      contactUs: 'Contactează-ne'
    },
    services: {
      title: 'Serviciile noastre',
      subtitle: 'Oferim soluții complete pentru sistemele audio și multimedia ale mașinii tale',
      multimedia: 'Reparații unități & multimedia',
      multimediaDesc: 'Reparații unități radio, head unit, display-uri, touchscreen și panouri de comandă',
      audio: 'Reparații amplificatoare audio',
      audioDesc: 'Reparații amplificatoare auto, difuzoare și sisteme audio de toate tipurile',
      electronic: 'Electronică & diagnosticare',
      electronicDesc: 'Diagnosticare și reparații module electronice, CAN bus, ECU/BCM',
      carplay: 'Sisteme VW/Skoda/Seat MIB',
      carplayDesc: 'Recuperare software MIB, înlocuire touchscreen, actualizare hărți, CarPlay/Android Auto',
      oem: 'Porsche PCM & Premium',
      oemDesc: 'Reparații Porsche PCM, sisteme BMW/Audi/Mercedes și actualizări firmware premium',
      accessories: 'Android Auto & Firmware',
      accessoriesDesc: 'Reparații stereo Android/Windows, firmware Kia/Hyundai, DVD/Blu-ray și televizoare auto',
      bookService: 'Programează-te',
      learnMore: 'Află mai mult',
      brandsTitle: 'Mărci auto deservite',
      ctaTitle: 'Nu găsești serviciul de care ai nevoie?',
      ctaDesc: 'Contactează-ne și vom găsi cea mai bună soluție pentru mașina ta.',
    },
    about: {
      title: 'Despre noi',
      subtitle: 'Pasionați de tehnologia auto din 2004',
      story: 'Povestea noastră',
      storyText: 'Car Audio Service a luat naștere în 2004 din pasiunea pentru tehnologia auto. De-a lungul anilor, am crescut de la un mic atelier la un centru de service complet, deservind mii de clienți din Chișinău și împrejurimi. Echipa noastră este formată din tehnicieni certificați cu experiență vastă în sisteme multimedia, audio și electronice auto.',
      mission: 'Misiunea noastră',
      missionText: 'Ne dedicăm să oferim servicii de cea mai înaltă calitate, folosind echipamente moderne și piese originale. Fiecare client beneficiază de diagnoză gratuită și consultanță profesională.',
      team: 'Echipa noastră',
      member1Name: 'Alexandru Soimu',
      member1Role: 'Fondator & Senior Technician',
      member1Bio: 'Peste 20 ani experiență în sisteme auto. Certificat BMW, Audi, Mercedes.',
      member2Name: 'Ion Ceban',
      member2Role: 'Multimedia Specialist',
      member2Bio: 'Expert în sisteme navigație și multimedia. Certificat Alpine & Pioneer.',
      member3Name: 'Dmitri Vasile',
      member3Role: 'Electronics Engineer',
      member3Bio: 'Inginer electronică auto, specialist CAN bus și module ECU.',
      certTitle: 'Certificări & Parteneriate',
      warranty: 'Garanție 3-12 luni la toate serviciile',
      freeCheck: 'Diagnoză gratuită',
      origParts: 'Piese originale și certificate',
      quickService: 'Serviciu rapid, de regulă în aceeași zi',
      founded: 'Fondare',
      clients: 'Clienți',
      satisfaction: 'Satisfacție',
      yearsExp: 'Ani experiență',
    },
    gallery: {
      title: 'Galerie',
      subtitle: 'O privire în atelierul nostru și lucrările realizate',
      all: 'Toate', multimedia: 'Multimedia', audio: 'Audio', electronic: 'Electronică',
      item1: 'Porsche PCM — selecție navigație',
      item2: 'VW RCD — sistem DAB radio',
      item3: 'Porsche PCM — unitate reparată',
      item4: 'Skoda MIB — meniu media',
      item5: 'VW MIB — navigație GPS activ',
    },
    location: {
      title: 'Locația noastră',
      subtitle: 'Vino să ne vizitezi — suntem în centrul Chișinăului',
      address: 'Strada Tudor Vladimirescu 3, MD-2024, Chișinău',
      phone: 'Telefon',
      email: 'Email',
      hours: 'Program de lucru',
      monFri: 'Luni - Vineri',
      sat: 'Sâmbătă',
      sun: 'Duminică',
      closed: 'Închis',
      getDirections: 'Obține indicații',
      contactForm: 'Trimite un mesaj',
      name: 'Numele tău',
      phone2: 'Număr de telefon',
      message: 'Mesajul tău',
      send: 'Trimite mesajul',
      sending: 'Se trimite...',
      sent: 'Mesaj trimis! Vă vom contacta în curând.',
      phoneRequired: 'Telefonul este obligatoriu',
      messageRequired: 'Mesajul este obligatoriu',
      photoLabel: 'Fotografie (opțional)',
      removePhoto: 'Elimină',
      addPhoto: 'Adaugă fotografie',
      photoHint: 'JPG, PNG, WEBP — max 5 MB',
    },
    auth: {
      loginTitle: 'Autentificare',
      registerTitle: 'Înregistrare cont',
      email: 'Email',
      password: 'Parolă',
      confirmPassword: 'Confirmă parola',
      name: 'Numele complet',
      phone: 'Telefon (opțional)',
      loginBtn: 'Intră în cont',
      registerBtn: 'Creează cont',
      noAccount: 'Nu ai cont?',
      haveAccount: 'Ai deja cont?',
      registerLink: 'Înregistrează-te',
      loginLink: 'Autentifică-te',
      forgotPass: 'Ai uitat parola?',
      errors: {
        emailRequired: 'Email-ul este obligatoriu',
        emailInvalid: 'Email invalid',
        passRequired: 'Parola este obligatorie',
        passMin: 'Parola trebuie să aibă minim 6 caractere',
        passMatch: 'Parolele nu se potrivesc',
        nameRequired: 'Numele este obligatoriu'
      }
    },
    profile: {
      title: 'Profilul meu',
      edit: 'Editează profilul',
      save: 'Salvează',
      cancel: 'Anulează',
      name: 'Nume',
      email: 'Email',
      phone: 'Telefon',
      role: 'Rol',
      member: 'Membru din',
      theme: 'Tema interfeței',
      language: 'Limba',
      exportData: 'Exportă datele mele',
      exportCSV: 'Export CSV',
      exportPDF: 'Export PDF',
      darkTheme: 'Întunecat',
      lightTheme: 'Deschis'
    },
    admin: {
      title: 'Panou Admin',
      users: 'Utilizatori',
      services: 'Servicii',
      messages: 'Mesaje',
      addService: 'Adaugă serviciu',
      editService: 'Editează serviciu',
      deleteService: 'Șterge serviciu',
      addUser: 'Adaugă utilizator',
      editUser: 'Editează utilizator',
      deleteUser: 'Șterge utilizator',
      name: 'Nume', email: 'Email', role: 'Rol', price: 'Preț',
      category: 'Categorie', description: 'Descriere',
      save: 'Salvează', cancel: 'Anulează',
      confirmDelete: 'Sigur vrei să ștergi?'
    },
    features: {
      exp: '20+ ani experiență', expDesc: 'Tehnicieni cu expertiză vastă în reparații audio și multimedia auto de toate mărcile',
      diag: 'Diagnoză gratuită', diagDesc: 'Diagnoză gratuită pentru echipamentele aduse demontate, fără costuri ascunse',
      warranty: 'Garanție 3-12 luni', warrantyDesc: 'Garanție completă la toate lucrările executate, în funcție de complexitate',
      db: 'Baze de date proprii', dbDesc: 'Deținem baze de date proprietare cu software, dump-uri de memorie și firmware',
      equip: 'Echipamente moderne', equipDesc: 'Testare modulară cu echipamente profesionale pentru diagnosticare precisă',
      corp: 'Plată corporativă', corpDesc: 'Acceptăm plata cashless pentru clienți corporativi și persoane juridice',
    },
    cta: {
      title: 'Programează-te acum',
      desc: 'Contactează-ne și rezolvăm problema ta auto rapid și profesional',
    },
    common: {
      loading: 'Se încarcă...', error: 'A apărut o eroare', success: 'Succes',
      save: 'Salvează', cancel: 'Anulează', delete: 'Șterge', edit: 'Editează',
      add: 'Adaugă', close: 'Închide', learnMore: 'Află mai mult', back: 'Înapoi',
      darkMode: 'Mod întunecat', lightMode: 'Mod deschis',
      navigation: 'Navigare', contact: 'Contact', allRights: 'Toate drepturile rezervate.',
    }
  },
  en: {
    nav: {
      home: 'Home', services: 'Services', about: 'About us',
      gallery: 'Gallery', location: 'Location', login: 'Login',
      register: 'Register', profile: 'Profile', logout: 'Logout', admin: 'Admin'
    },
    home: {
      hero1: 'Your expert in car audio & multimedia systems',
      hero2: 'Fast and professional repairs',
      hero3: 'Guaranteed quality, fair prices',
      hero4: 'Complete services for your car',
      cta: 'View services',
      whyUs: 'Why choose us?',
      years: 'Years experience',
      clients: 'Happy clients',
      warranty: 'Warranty',
      brands: 'Car brands served',
      featuredServices: 'Main services',
      bookNow: 'Book now',
      contactUs: 'Contact us'
    },
    services: {
      title: 'Our Services',
      subtitle: 'We offer complete solutions for your car\'s audio and multimedia systems',
      multimedia: 'Head Unit & Multimedia Repairs',
      multimediaDesc: 'Repairs of radio units, head units, displays, touchscreens and control panels',
      audio: 'Audio Amplifier Repairs',
      audioDesc: 'Repairs of car amplifiers, speakers and all types of car audio systems',
      electronic: 'Electronics & Diagnostics',
      electronicDesc: 'Diagnostics and repair of electronic modules, CAN bus, ECU/BCM',
      carplay: 'VW/Skoda/Seat MIB Systems',
      carplayDesc: 'MIB software recovery, touchscreen replacement, map updates, CarPlay/Android Auto',
      oem: 'Porsche PCM & Premium',
      oemDesc: 'Porsche PCM repairs, BMW/Audi/Mercedes systems and premium firmware updates',
      accessories: 'Android Stereo & Firmware',
      accessoriesDesc: 'Android/Windows stereo repairs, Kia/Hyundai firmware, DVD/Blu-ray and car TVs',
      bookService: 'Book service',
      learnMore: 'Learn more',
      brandsTitle: 'Car brands served',
      ctaTitle: "Can't find the service you need?",
      ctaDesc: "Contact us and we'll find the best solution for your car.",
    },
    about: {
      title: 'About us',
      subtitle: 'Passionate about automotive technology since 2004',
      story: 'Our story',
      storyText: 'Car Audio Service was founded in 2004 out of a passion for automotive technology. Over the years, we\'ve grown from a small workshop to a full-service center, serving thousands of clients from Chisinau and surroundings. Our team consists of certified technicians with extensive experience in multimedia, audio and automotive electronics.',
      mission: 'Our mission',
      missionText: 'We are dedicated to providing the highest quality services, using modern equipment and original parts. Every client benefits from free diagnostics and professional consultation.',
      team: 'Our team',
      member1Name: 'Alexandru Soimu',
      member1Role: 'Founder & Senior Technician',
      member1Bio: 'Over 20 years experience in automotive systems. BMW, Audi, Mercedes certified.',
      member2Name: 'Ion Ceban',
      member2Role: 'Multimedia Specialist',
      member2Bio: 'Navigation and multimedia systems expert. Alpine & Pioneer certified.',
      member3Name: 'Dmitri Vasile',
      member3Role: 'Electronics Engineer',
      member3Bio: 'Automotive electronics engineer, CAN bus and ECU module specialist.',
      certTitle: 'Certifications & Partnerships',
      warranty: '3-12 months warranty on all services',
      freeCheck: 'Free diagnostics',
      origParts: 'Original and certified parts',
      quickService: 'Fast service, usually same day',
      founded: 'Founded',
      clients: 'Clients',
      satisfaction: 'Satisfaction',
      yearsExp: 'Years experience',
    },
    gallery: {
      title: 'Gallery',
      subtitle: 'A look at our workshop and completed work',
      all: 'All', multimedia: 'Multimedia', audio: 'Audio', electronic: 'Electronics',
      item1: 'Porsche PCM — navigation menu',
      item2: 'VW RCD — DAB radio system',
      item3: 'Porsche PCM — repaired unit',
      item4: 'Skoda MIB — media menu',
      item5: 'VW MIB — active GPS navigation',
    },
    location: {
      title: 'Our Location',
      subtitle: 'Come visit us — we\'re in the heart of Chisinau',
      address: 'Tudor Vladimirescu 3, MD-2024, Chisinau, Moldova',
      phone: 'Phone',
      email: 'Email',
      hours: 'Working hours',
      monFri: 'Monday - Friday',
      sat: 'Saturday',
      sun: 'Sunday',
      closed: 'Closed',
      getDirections: 'Get directions',
      contactForm: 'Send a message',
      name: 'Your name',
      phone2: 'Phone number',
      message: 'Your message',
      send: 'Send message',
      sending: 'Sending...',
      sent: "Message sent! We'll contact you soon.",
      phoneRequired: 'Phone number is required',
      messageRequired: 'Message is required',
      photoLabel: 'Photo (optional)',
      removePhoto: 'Remove',
      addPhoto: 'Add photo',
      photoHint: 'JPG, PNG, WEBP — max 5 MB',
    },
    auth: {
      loginTitle: 'Login',
      registerTitle: 'Create account',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm password',
      name: 'Full name',
      phone: 'Phone (optional)',
      loginBtn: 'Sign in',
      registerBtn: 'Create account',
      noAccount: 'Don\'t have an account?',
      haveAccount: 'Already have an account?',
      registerLink: 'Register',
      loginLink: 'Login',
      forgotPass: 'Forgot password?',
      errors: {
        emailRequired: 'Email is required',
        emailInvalid: 'Invalid email',
        passRequired: 'Password is required',
        passMin: 'Password must be at least 6 characters',
        passMatch: 'Passwords don\'t match',
        nameRequired: 'Name is required'
      }
    },
    profile: {
      title: 'My Profile',
      edit: 'Edit profile',
      save: 'Save',
      cancel: 'Cancel',
      name: 'Name',
      email: 'Email',
      phone: 'Phone',
      role: 'Role',
      member: 'Member since',
      theme: 'Interface theme',
      language: 'Language',
      exportData: 'Export my data',
      exportCSV: 'Export CSV',
      exportPDF: 'Export PDF',
      darkTheme: 'Dark',
      lightTheme: 'Light'
    },
    admin: {
      title: 'Admin Panel',
      users: 'Users',
      services: 'Services',
      messages: 'Messages',
      addService: 'Add service',
      editService: 'Edit service',
      deleteService: 'Delete service',
      addUser: 'Add user',
      editUser: 'Edit user',
      deleteUser: 'Delete user',
      name: 'Name', email: 'Email', role: 'Role', price: 'Price',
      category: 'Category', description: 'Description',
      save: 'Save', cancel: 'Cancel',
      confirmDelete: 'Are you sure you want to delete?'
    },
    features: {
      exp: '20+ years experience', expDesc: 'Technicians with vast expertise in car audio and multimedia repairs of all brands',
      diag: 'Free diagnostics', diagDesc: 'Free diagnostics for dismantled equipment brought in, no hidden costs',
      warranty: '3-12 month warranty', warrantyDesc: 'Full warranty on all completed work, depending on complexity',
      db: 'Proprietary databases', dbDesc: 'We hold proprietary databases of software, memory dumps and firmware',
      equip: 'Modern equipment', equipDesc: 'Modular testing with professional equipment for precise diagnostics',
      corp: 'Corporate payment', corpDesc: 'We accept cashless payments for corporate clients and legal entities',
    },
    cta: {
      title: 'Book now',
      desc: 'Contact us and we\'ll fix your car problem fast and professionally',
    },
    common: {
      loading: 'Loading...', error: 'An error occurred', success: 'Success',
      save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit',
      add: 'Add', close: 'Close', learnMore: 'Learn more', back: 'Back',
      darkMode: 'Dark mode', lightMode: 'Light mode',
      navigation: 'Navigation', contact: 'Contact', allRights: 'All rights reserved.',
    }
  },
  ru: {
    nav: {
      home: 'Главная', services: 'Услуги', about: 'О нас',
      gallery: 'Галерея', location: 'Местоположение', login: 'Войти',
      register: 'Регистрация', profile: 'Профиль', logout: 'Выйти', admin: 'Админ'
    },
    home: {
      hero1: 'Эксперт по автомобильным аудио и мультимедиа системам',
      hero2: 'Быстрый и профессиональный ремонт',
      hero3: 'Гарантированное качество, честные цены',
      hero4: 'Комплексное обслуживание вашего автомобиля',
      cta: 'Смотреть услуги',
      whyUs: 'Почему выбирают нас?',
      years: 'Лет опыта',
      clients: 'Довольных клиентов',
      warranty: 'Гарантия',
      brands: 'Обслуживаемых марок',
      featuredServices: 'Основные услуги',
      bookNow: 'Записаться',
      contactUs: 'Связаться с нами'
    },
    services: {
      title: 'Наши услуги',
      subtitle: 'Предлагаем полные решения для аудио и мультимедиа систем вашего автомобиля',
      multimedia: 'Ремонт магнитол и мультимедиа',
      multimediaDesc: 'Ремонт автомагнитол, head unit, дисплеев, тачскринов и панелей управления',
      audio: 'Ремонт усилителей и аудио',
      audioDesc: 'Ремонт автомобильных усилителей, динамиков и аудиосистем всех типов',
      electronic: 'Электроника и диагностика',
      electronicDesc: 'Диагностика и ремонт электронных модулей, CAN bus, ECU/BCM',
      carplay: 'Системы VW/Skoda/Seat MIB',
      carplayDesc: 'Восстановление ПО MIB, замена тачскрина, обновление карт, CarPlay/Android Auto',
      oem: 'Porsche PCM и премиум системы',
      oemDesc: 'Ремонт Porsche PCM, системы BMW/Audi/Mercedes и обновление премиум прошивок',
      accessories: 'Android магнитолы и прошивки',
      accessoriesDesc: 'Ремонт Android/Windows магнитол, прошивка Kia/Hyundai, DVD/Blu-ray и автотелевизоры',
      bookService: 'Записаться',
      learnMore: 'Подробнее',
      brandsTitle: 'Обслуживаемые марки автомобилей',
      ctaTitle: 'Не нашли нужную услугу?',
      ctaDesc: 'Свяжитесь с нами, и мы найдём лучшее решение для вашего автомобиля.',
    },
    about: {
      title: 'О нас',
      subtitle: 'Увлечённые автомобильными технологиями с 2004 года',
      story: 'Наша история',
      storyText: 'Car Audio Service основан в 2004 году из страсти к автомобильным технологиям. За эти годы мы выросли из небольшой мастерской в полноценный сервисный центр, обслуживая тысячи клиентов из Кишинёва и окрестностей. Наша команда состоит из сертифицированных техников с обширным опытом в мультимедийных, аудио и автомобильных электронных системах.',
      mission: 'Наша миссия',
      missionText: 'Мы посвящаем себя предоставлению услуг высочайшего качества, используя современное оборудование и оригинальные запчасти. Каждый клиент получает бесплатную диагностику и профессиональную консультацию.',
      team: 'Наша команда',
      member1Name: 'Александру Соймэ',
      member1Role: 'Основатель & Старший техник',
      member1Bio: 'Более 20 лет опыта в автомобильных системах. Сертификат BMW, Audi, Mercedes.',
      member2Name: 'Ион Чебан',
      member2Role: 'Специалист по мультимедиа',
      member2Bio: 'Эксперт по системам навигации и мультимедиа. Сертификат Alpine & Pioneer.',
      member3Name: 'Дмитрий Василе',
      member3Role: 'Инженер-электронщик',
      member3Bio: 'Инженер автоэлектроники, специалист CAN bus и модулей ECU.',
      certTitle: 'Сертификаты и партнёрства',
      warranty: 'Гарантия 3-12 месяцев на все услуги',
      freeCheck: 'Бесплатная диагностика',
      origParts: 'Оригинальные и сертифицированные запчасти',
      quickService: 'Быстрое обслуживание, как правило, в тот же день',
      founded: 'Основание',
      clients: 'Клиенты',
      satisfaction: 'Удовлетворение',
      yearsExp: 'Лет опыта',
    },
    gallery: {
      title: 'Галерея',
      subtitle: 'Взгляд в нашу мастерскую и выполненные работы',
      all: 'Все', multimedia: 'Мультимедиа', audio: 'Аудио', electronic: 'Электроника',
      item1: 'Porsche PCM — меню навигации',
      item2: 'VW RCD — система DAB радио',
      item3: 'Porsche PCM — отремонтированный блок',
      item4: 'Skoda MIB — меню медиа',
      item5: 'VW MIB — активная GPS навигация',
    },
    location: {
      title: 'Наше местоположение',
      subtitle: 'Приходите к нам — мы в центре Кишинёва',
      address: 'Улица Тудор Владимиреску 3, MD-2024, Кишинёв',
      phone: 'Телефон',
      email: 'Email',
      hours: 'Часы работы',
      monFri: 'Понедельник - Пятница',
      sat: 'Суббота',
      sun: 'Воскресенье',
      closed: 'Закрыто',
      getDirections: 'Проложить маршрут',
      contactForm: 'Отправить сообщение',
      name: 'Ваше имя',
      phone2: 'Номер телефона',
      message: 'Ваше сообщение',
      send: 'Отправить',
      sending: 'Отправка...',
      sent: 'Сообщение отправлено! Мы свяжемся с вами в ближайшее время.',
      phoneRequired: 'Телефон обязателен',
      messageRequired: 'Сообщение обязательно',
      photoLabel: 'Фото (необязательно)',
      removePhoto: 'Удалить',
      addPhoto: 'Добавить фото',
      photoHint: 'JPG, PNG, WEBP — макс. 5 МБ',
    },
    auth: {
      loginTitle: 'Войти',
      registerTitle: 'Создать аккаунт',
      email: 'Email',
      password: 'Пароль',
      confirmPassword: 'Подтвердите пароль',
      name: 'Полное имя',
      phone: 'Телефон (необязательно)',
      loginBtn: 'Войти',
      registerBtn: 'Создать аккаунт',
      noAccount: 'Нет аккаунта?',
      haveAccount: 'Уже есть аккаунт?',
      registerLink: 'Зарегистрироваться',
      loginLink: 'Войти',
      forgotPass: 'Забыли пароль?',
      errors: {
        emailRequired: 'Email обязателен',
        emailInvalid: 'Неверный email',
        passRequired: 'Пароль обязателен',
        passMin: 'Пароль должен содержать минимум 6 символов',
        passMatch: 'Пароли не совпадают',
        nameRequired: 'Имя обязательно'
      }
    },
    profile: {
      title: 'Мой профиль',
      edit: 'Редактировать профиль',
      save: 'Сохранить',
      cancel: 'Отмена',
      name: 'Имя',
      email: 'Email',
      phone: 'Телефон',
      role: 'Роль',
      member: 'Участник с',
      theme: 'Тема интерфейса',
      language: 'Язык',
      exportData: 'Экспортировать мои данные',
      exportCSV: 'Экспорт CSV',
      exportPDF: 'Экспорт PDF',
      darkTheme: 'Тёмная',
      lightTheme: 'Светлая'
    },
    admin: {
      title: 'Панель администратора',
      users: 'Пользователи',
      services: 'Услуги',
      messages: 'Сообщения',
      addService: 'Добавить услугу',
      editService: 'Редактировать услугу',
      deleteService: 'Удалить услугу',
      addUser: 'Добавить пользователя',
      editUser: 'Редактировать пользователя',
      deleteUser: 'Удалить пользователя',
      name: 'Имя', email: 'Email', role: 'Роль', price: 'Цена',
      category: 'Категория', description: 'Описание',
      save: 'Сохранить', cancel: 'Отмена',
      confirmDelete: 'Вы уверены, что хотите удалить?'
    },
    features: {
      exp: '20+ лет опыта', expDesc: 'Техники с обширной экспертизой в ремонте автоаудио и мультимедиа всех марок',
      diag: 'Бесплатная диагностика', diagDesc: 'Бесплатная диагностика для демонтированного оборудования, без скрытых расходов',
      warranty: 'Гарантия 3-12 месяцев', warrantyDesc: 'Полная гарантия на все выполненные работы, в зависимости от сложности',
      db: 'Собственные базы данных', dbDesc: 'Располагаем собственными базами ПО, дампов памяти и прошивок',
      equip: 'Современное оборудование', equipDesc: 'Модульное тестирование профессиональным оборудованием для точной диагностики',
      corp: 'Корпоративная оплата', corpDesc: 'Принимаем безналичную оплату для корпоративных клиентов и юридических лиц',
    },
    cta: {
      title: 'Записаться сейчас',
      desc: 'Свяжитесь с нами, и мы быстро и профессионально решим вашу проблему',
    },
    common: {
      loading: 'Загрузка...', error: 'Произошла ошибка', success: 'Успешно',
      save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', edit: 'Редактировать',
      add: 'Добавить', close: 'Закрыть', learnMore: 'Подробнее', back: 'Назад',
      darkMode: 'Тёмный режим', lightMode: 'Светлый режим',
      navigation: 'Навигация', contact: 'Контакты', allRights: 'Все права защищены.',
    }
  },
  cs: {
    nav: {
      home: 'Domů', services: 'Služby', about: 'O nás',
      gallery: 'Galerie', location: 'Poloha', login: 'Přihlásit',
      register: 'Registrace', profile: 'Profil', logout: 'Odhlásit', admin: 'Admin'
    },
    home: {
      hero1: 'Váš expert na auto audio a multimediální systémy',
      hero2: 'Rychlé a profesionální opravy',
      hero3: 'Zaručená kvalita, férové ceny',
      hero4: 'Kompletní služby pro vaše auto',
      cta: 'Zobrazit služby',
      whyUs: 'Proč si vybrat nás?',
      years: 'Let zkušeností',
      clients: 'Spokojených klientů',
      warranty: 'Záruka',
      brands: 'Obsluhovaných značek',
      featuredServices: 'Hlavní služby',
      bookNow: 'Rezervovat',
      contactUs: 'Kontaktujte nás'
    },
    services: {
      title: 'Naše služby',
      subtitle: 'Nabízíme kompletní řešení pro audio a multimediální systémy vašeho auta',
      multimedia: 'Opravy autorádií a multimédií',
      multimediaDesc: 'Opravy autorádií, head unit, displejů, dotykových obrazovek a ovládacích panelů',
      audio: 'Opravy zesilovačů a audia',
      audioDesc: 'Opravy automobilových zesilovačů, reproduktorů a audio systémů všech typů',
      electronic: 'Elektronika a diagnostika',
      electronicDesc: 'Diagnostika a opravy elektronických modulů, CAN bus, ECU/BCM',
      carplay: 'Systémy VW/Skoda/Seat MIB',
      carplayDesc: 'Obnova SW MIB, výměna dotykové obrazovky, aktualizace map, CarPlay/Android Auto',
      oem: 'Porsche PCM a prémiové systémy',
      oemDesc: 'Opravy Porsche PCM, systémy BMW/Audi/Mercedes a aktualizace prémiového firmwaru',
      accessories: 'Android rádia a firmware',
      accessoriesDesc: 'Opravy Android/Windows autorádií, firmware Kia/Hyundai, DVD/Blu-ray a auto TV',
      bookService: 'Rezervovat',
      learnMore: 'Více informací',
      brandsTitle: 'Obsluhované značky aut',
      ctaTitle: 'Nenašli jste hledanou službu?',
      ctaDesc: 'Kontaktujte nás a najdeme nejlepší řešení pro vaše auto.',
    },
    about: {
      title: 'O nás',
      subtitle: 'Nadšenci pro automobilové technologie od roku 2004',
      story: 'Náš příběh',
      storyText: 'Car Audio Service byl založen v roce 2004 z vášně pro automobilové technologie. V průběhu let jsme vyrostli z malé dílny na plnohodnotné servisní centrum, obsluhující tisíce klientů z Kišiněva a okolí. Náš tým tvoří certifikovaní technici s rozsáhlými zkušenostmi v multimediálních, audio a automobilových elektronických systémech.',
      mission: 'Naše mise',
      missionText: 'Věnujeme se poskytování služeb nejvyšší kvality pomocí moderního vybavení a originálních dílů. Každý klient získá bezplatnou diagnostiku a profesionální poradenství.',
      team: 'Náš tým',
      member1Name: 'Alexandru Soimu',
      member1Role: 'Zakladatel & Hlavní technik',
      member1Bio: 'Přes 20 let zkušeností v automobilových systémech. Certifikát BMW, Audi, Mercedes.',
      member2Name: 'Ion Ceban',
      member2Role: 'Multimediální specialista',
      member2Bio: 'Expert na navigační a multimediální systémy. Certifikát Alpine & Pioneer.',
      member3Name: 'Dmitri Vasile',
      member3Role: 'Elektrotechnický inženýr',
      member3Bio: 'Inženýr automobilové elektroniky, specialista CAN bus a ECU modulů.',
      certTitle: 'Certifikace & Partnerství',
      warranty: 'Záruka 3–12 měsíců na všechny služby',
      freeCheck: 'Bezplatná diagnostika',
      origParts: 'Originální a certifikované díly',
      quickService: 'Rychlá oprava, obvykle tentýž den',
      founded: 'Rok vzniku',
      clients: 'Klienti',
      satisfaction: 'Spokojenost',
      yearsExp: 'Let zkušeností',
    },
    gallery: {
      title: 'Galerie',
      subtitle: 'Pohled do naší dílny a dokončených prací',
      all: 'Vše', multimedia: 'Multimedia', audio: 'Audio', electronic: 'Elektronika',
      item1: 'Porsche PCM — menu navigace',
      item2: 'VW RCD — systém DAB rádio',
      item3: 'Porsche PCM — opravená jednotka',
      item4: 'Skoda MIB — menu médií',
      item5: 'VW MIB — aktivní GPS navigace',
    },
    location: {
      title: 'Naše poloha',
      subtitle: 'Přijďte nás navštívit — jsme v centru Kišiněva',
      address: 'Ulice Tudor Vladimirescu 3, MD-2024, Kišiněv',
      phone: 'Telefon',
      email: 'Email',
      hours: 'Pracovní doba',
      monFri: 'Pondělí – Pátek',
      sat: 'Sobota',
      sun: 'Neděle',
      closed: 'Zavřeno',
      getDirections: 'Navigovat',
      contactForm: 'Poslat zprávu',
      name: 'Vaše jméno',
      phone2: 'Telefonní číslo',
      message: 'Vaše zpráva',
      send: 'Odeslat zprávu',
      sending: 'Odesílání...',
      sent: 'Zpráva odeslána! Brzy vás kontaktujeme.',
      phoneRequired: 'Telefon je povinný',
      messageRequired: 'Zpráva je povinná',
      photoLabel: 'Fotografie (volitelné)',
      removePhoto: 'Odstranit',
      addPhoto: 'Přidat fotku',
      photoHint: 'JPG, PNG, WEBP — max 5 MB',
    },
    auth: {
      loginTitle: 'Přihlášení',
      registerTitle: 'Vytvořit účet',
      email: 'Email',
      password: 'Heslo',
      confirmPassword: 'Potvrdit heslo',
      name: 'Celé jméno',
      phone: 'Telefon (volitelné)',
      loginBtn: 'Přihlásit se',
      registerBtn: 'Vytvořit účet',
      noAccount: 'Nemáte účet?',
      haveAccount: 'Již máte účet?',
      registerLink: 'Registrovat se',
      loginLink: 'Přihlásit se',
      forgotPass: 'Zapomenuté heslo?',
      errors: {
        emailRequired: 'Email je povinný',
        emailInvalid: 'Neplatný email',
        passRequired: 'Heslo je povinné',
        passMin: 'Heslo musí mít alespoň 6 znaků',
        passMatch: 'Hesla se neshodují',
        nameRequired: 'Jméno je povinné'
      }
    },
    profile: {
      title: 'Můj profil',
      edit: 'Upravit profil',
      save: 'Uložit',
      cancel: 'Zrušit',
      name: 'Jméno',
      email: 'Email',
      phone: 'Telefon',
      role: 'Role',
      member: 'Člen od',
      theme: 'Téma rozhraní',
      language: 'Jazyk',
      exportData: 'Exportovat moje data',
      exportCSV: 'Export CSV',
      exportPDF: 'Export PDF',
      darkTheme: 'Tmavé',
      lightTheme: 'Světlé'
    },
    admin: {
      title: 'Administrátorský panel',
      users: 'Uživatelé',
      services: 'Služby',
      messages: 'Zprávy',
      addService: 'Přidat službu',
      editService: 'Upravit službu',
      deleteService: 'Smazat službu',
      addUser: 'Přidat uživatele',
      editUser: 'Upravit uživatele',
      deleteUser: 'Smazat uživatele',
      name: 'Jméno', email: 'Email', role: 'Role', price: 'Cena',
      category: 'Kategorie', description: 'Popis',
      save: 'Uložit', cancel: 'Zrušit',
      confirmDelete: 'Opravdu chcete smazat?'
    },
    features: {
      exp: '20+ let zkušeností', expDesc: 'Technici s rozsáhlými znalostmi v opravách autoaudia a multimédií všech značek',
      diag: 'Bezplatná diagnostika', diagDesc: 'Bezplatná diagnostika pro demontované zařízení, bez skrytých nákladů',
      warranty: 'Záruka 3-12 měsíců', warrantyDesc: 'Plná záruka na všechny provedené práce, v závislosti na složitosti',
      db: 'Vlastní databáze', dbDesc: 'Disponujeme vlastními databázemi softwaru, paměťových dumpů a firmwarů',
      equip: 'Moderní vybavení', equipDesc: 'Modulární testování profesionálním vybavením pro přesnou diagnostiku',
      corp: 'Firemní platby', corpDesc: 'Přijímáme bezhotovostní platby pro firemní klienty a právnické osoby',
    },
    cta: {
      title: 'Rezervovat nyní',
      desc: 'Kontaktujte nás a rychle a profesionálně vyřešíme váš problém s autem',
    },
    common: {
      loading: 'Načítání...', error: 'Vyskytla se chyba', success: 'Úspěch',
      save: 'Uložit', cancel: 'Zrušit', delete: 'Smazat', edit: 'Upravit',
      add: 'Přidat', close: 'Zavřít', learnMore: 'Více informací', back: 'Zpět',
      darkMode: 'Tmavý režim', lightMode: 'Světlý režim',
      navigation: 'Navigace', contact: 'Kontakt', allRights: 'Všechna práva vyhrazena.',
    }
  }
};

const LangContext = createContext();

export function useLang() {
  return useContext(LangContext);
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'ro');

  function changeLang(newLang) {
    setLang(newLang);
    localStorage.setItem('lang', newLang);
  }

  const t = translations[lang] || translations.ro;

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}